// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewDepositRepository creates a new instance of DepositRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepositRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepositRepository {
	mock := &DepositRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DepositRepository is an autogenerated mock type for the DepositRepository type
type DepositRepository struct {
	mock.Mock
}

type DepositRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DepositRepository) EXPECT() *DepositRepository_Expecter {
	return &DepositRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type DepositRepository
func (_mock *DepositRepository) Create(ctx context.Context, input domain.CreateDeposit, audit *domain.AuditEntry) (*domain.Deposit, error) {
	ret := _mock.Called(ctx, input, audit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Deposit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateDeposit, *domain.AuditEntry) (*domain.Deposit, error)); ok {
		return returnFunc(ctx, input, audit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateDeposit, *domain.AuditEntry) *domain.Deposit); ok {
		r0 = returnFunc(ctx, input, audit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateDeposit, *domain.AuditEntry) error); ok {
		r1 = returnFunc(ctx, input, audit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepositRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DepositRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.CreateDeposit
//   - audit *domain.AuditEntry
func (_e *DepositRepository_Expecter) Create(ctx any, input any, audit any) *DepositRepository_Create_Call {
	return &DepositRepository_Create_Call{Call: _e.mock.On("Create", ctx, input, audit)}
}

func (_c *DepositRepository_Create_Call) Run(run func(ctx context.Context, input domain.CreateDeposit, audit *domain.AuditEntry)) *DepositRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateDeposit
		if args[1] != nil {
			arg1 = args[1].(domain.CreateDeposit)
		}
		var arg2 *domain.AuditEntry
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DepositRepository_Create_Call) Return(deposit *domain.Deposit, err error) *DepositRepository_Create_Call {
	_c.Call.Return(deposit, err)
	return _c
}

func (_c *DepositRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input domain.CreateDeposit, audit *domain.AuditEntry) (*domain.Deposit, error)) *DepositRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type DepositRepository
func (_mock *DepositRepository) GetByID(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Deposit, error) {
	ret := _mock.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Deposit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Deposit, error)); ok {
		return returnFunc(ctx, merchantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Deposit); ok {
		r0 = returnFunc(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepositRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DepositRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *DepositRepository_Expecter) GetByID(ctx any, merchantID any, id any) *DepositRepository_GetByID_Call {
	return &DepositRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, merchantID, id)}
}

func (_c *DepositRepository_GetByID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *DepositRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DepositRepository_GetByID_Call) Return(deposit *domain.Deposit, err error) *DepositRepository_GetByID_Call {
	_c.Call.Return(deposit, err)
	return _c
}

func (_c *DepositRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Deposit, error)) *DepositRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type DepositRepository
func (_mock *DepositRepository) List(ctx context.Context, query domain.DepositQuery) ([]domain.Deposit, int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Deposit
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DepositQuery) ([]domain.Deposit, int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DepositQuery) []domain.Deposit); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DepositQuery) int64); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.DepositQuery) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DepositRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DepositRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.DepositQuery
func (_e *DepositRepository_Expecter) List(ctx any, query any) *DepositRepository_List_Call {
	return &DepositRepository_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *DepositRepository_List_Call) Run(run func(ctx context.Context, query domain.DepositQuery)) *DepositRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DepositQuery
		if args[1] != nil {
			arg1 = args[1].(domain.DepositQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DepositRepository_List_Call) Return(deposits []domain.Deposit, n int64, err error) *DepositRepository_List_Call {
	_c.Call.Return(deposits, n, err)
	return _c
}

func (_c *DepositRepository_List_Call) RunAndReturn(run func(ctx context.Context, query domain.DepositQuery) ([]domain.Deposit, int64, error)) *DepositRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
