// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewDepositService creates a new instance of DepositService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepositService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepositService {
	mock := &DepositService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DepositService is an autogenerated mock type for the DepositService type
type DepositService struct {
	mock.Mock
}

type DepositService_Expecter struct {
	mock *mock.Mock
}

func (_m *DepositService) EXPECT() *DepositService_Expecter {
	return &DepositService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type DepositService
func (_mock *DepositService) Get(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Deposit, error) {
	ret := _mock.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Deposit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Deposit, error)); ok {
		return returnFunc(ctx, merchantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Deposit); ok {
		r0 = returnFunc(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepositService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DepositService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *DepositService_Expecter) Get(ctx any, merchantID any, id any) *DepositService_Get_Call {
	return &DepositService_Get_Call{Call: _e.mock.On("Get", ctx, merchantID, id)}
}

func (_c *DepositService_Get_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *DepositService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DepositService_Get_Call) Return(deposit *domain.Deposit, err error) *DepositService_Get_Call {
	_c.Call.Return(deposit, err)
	return _c
}

func (_c *DepositService_Get_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Deposit, error)) *DepositService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Initiate provides a mock function for the type DepositService
func (_mock *DepositService) Initiate(ctx context.Context, actor domain.Actor, input domain.InitiateDeposit) (*domain.Deposit, error) {
	ret := _mock.Called(ctx, actor, input)

	if len(ret) == 0 {
		panic("no return value specified for Initiate")
	}

	var r0 *domain.Deposit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Actor, domain.InitiateDeposit) (*domain.Deposit, error)); ok {
		return returnFunc(ctx, actor, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Actor, domain.InitiateDeposit) *domain.Deposit); ok {
		r0 = returnFunc(ctx, actor, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Actor, domain.InitiateDeposit) error); ok {
		r1 = returnFunc(ctx, actor, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepositService_Initiate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initiate'
type DepositService_Initiate_Call struct {
	*mock.Call
}

// Initiate is a helper method to define mock.On call
//   - ctx context.Context
//   - actor domain.Actor
//   - input domain.InitiateDeposit
func (_e *DepositService_Expecter) Initiate(ctx any, actor any, input any) *DepositService_Initiate_Call {
	return &DepositService_Initiate_Call{Call: _e.mock.On("Initiate", ctx, actor, input)}
}

func (_c *DepositService_Initiate_Call) Run(run func(ctx context.Context, actor domain.Actor, input domain.InitiateDeposit)) *DepositService_Initiate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Actor
		if args[1] != nil {
			arg1 = args[1].(domain.Actor)
		}
		var arg2 domain.InitiateDeposit
		if args[2] != nil {
			arg2 = args[2].(domain.InitiateDeposit)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DepositService_Initiate_Call) Return(deposit *domain.Deposit, err error) *DepositService_Initiate_Call {
	_c.Call.Return(deposit, err)
	return _c
}

func (_c *DepositService_Initiate_Call) RunAndReturn(run func(ctx context.Context, actor domain.Actor, input domain.InitiateDeposit) (*domain.Deposit, error)) *DepositService_Initiate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type DepositService
func (_mock *DepositService) List(ctx context.Context, query domain.DepositQuery) ([]domain.Deposit, int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Deposit
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DepositQuery) ([]domain.Deposit, int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DepositQuery) []domain.Deposit); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Deposit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DepositQuery) int64); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.DepositQuery) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DepositService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DepositService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.DepositQuery
func (_e *DepositService_Expecter) List(ctx any, query any) *DepositService_List_Call {
	return &DepositService_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *DepositService_List_Call) Run(run func(ctx context.Context, query domain.DepositQuery)) *DepositService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DepositQuery
		if args[1] != nil {
			arg1 = args[1].(domain.DepositQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DepositService_List_Call) Return(deposits []domain.Deposit, n int64, err error) *DepositService_List_Call {
	_c.Call.Return(deposits, n, err)
	return _c
}

func (_c *DepositService_List_Call) RunAndReturn(run func(ctx context.Context, query domain.DepositQuery) ([]domain.Deposit, int64, error)) *DepositService_List_Call {
	_c.Call.Return(run)
	return _c
}
