// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSummaryRepository creates a new instance of SummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SummaryRepository {
	mock := &SummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SummaryRepository is an autogenerated mock type for the SummaryRepository type
type SummaryRepository struct {
	mock.Mock
}

type SummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SummaryRepository) EXPECT() *SummaryRepository_Expecter {
	return &SummaryRepository_Expecter{mock: &_m.Mock}
}

// MerchantSummary provides a mock function for the type SummaryRepository
func (_mock *SummaryRepository) MerchantSummary(ctx context.Context, merchantID uuid.UUID, since time.Time) (*domain.MerchantSummary, error) {
	ret := _mock.Called(ctx, merchantID, since)

	if len(ret) == 0 {
		panic("no return value specified for MerchantSummary")
	}

	var r0 *domain.MerchantSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*domain.MerchantSummary, error)); ok {
		return returnFunc(ctx, merchantID, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *domain.MerchantSummary); ok {
		r0 = returnFunc(ctx, merchantID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MerchantSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, merchantID, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SummaryRepository_MerchantSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantSummary'
type SummaryRepository_MerchantSummary_Call struct {
	*mock.Call
}

// MerchantSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - since time.Time
func (_e *SummaryRepository_Expecter) MerchantSummary(ctx any, merchantID any, since any) *SummaryRepository_MerchantSummary_Call {
	return &SummaryRepository_MerchantSummary_Call{Call: _e.mock.On("MerchantSummary", ctx, merchantID, since)}
}

func (_c *SummaryRepository_MerchantSummary_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, since time.Time)) *SummaryRepository_MerchantSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SummaryRepository_MerchantSummary_Call) Return(merchantSummary *domain.MerchantSummary, err error) *SummaryRepository_MerchantSummary_Call {
	_c.Call.Return(merchantSummary, err)
	return _c
}

func (_c *SummaryRepository_MerchantSummary_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, since time.Time) (*domain.MerchantSummary, error)) *SummaryRepository_MerchantSummary_Call {
	_c.Call.Return(run)
	return _c
}
