// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSummaryService creates a new instance of SummaryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSummaryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SummaryService {
	mock := &SummaryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SummaryService is an autogenerated mock type for the SummaryService type
type SummaryService struct {
	mock.Mock
}

type SummaryService_Expecter struct {
	mock *mock.Mock
}

func (_m *SummaryService) EXPECT() *SummaryService_Expecter {
	return &SummaryService_Expecter{mock: &_m.Mock}
}

// Merchant provides a mock function for the type SummaryService
func (_mock *SummaryService) Merchant(ctx context.Context, merchantID uuid.UUID) (*domain.MerchantSummary, error) {
	ret := _mock.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for Merchant")
	}

	var r0 *domain.MerchantSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.MerchantSummary, error)); ok {
		return returnFunc(ctx, merchantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.MerchantSummary); ok {
		r0 = returnFunc(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MerchantSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SummaryService_Merchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merchant'
type SummaryService_Merchant_Call struct {
	*mock.Call
}

// Merchant is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *SummaryService_Expecter) Merchant(ctx any, merchantID any) *SummaryService_Merchant_Call {
	return &SummaryService_Merchant_Call{Call: _e.mock.On("Merchant", ctx, merchantID)}
}

func (_c *SummaryService_Merchant_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *SummaryService_Merchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SummaryService_Merchant_Call) Return(merchantSummary *domain.MerchantSummary, err error) *SummaryService_Merchant_Call {
	_c.Call.Return(merchantSummary, err)
	return _c
}

func (_c *SummaryService_Merchant_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID) (*domain.MerchantSummary, error)) *SummaryService_Merchant_Call {
	_c.Call.Return(run)
	return _c
}
