// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mudflap-autobotz/payment-service-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTigerbaboonService creates a new instance of TigerbaboonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTigerbaboonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TigerbaboonService {
	mock := &TigerbaboonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TigerbaboonService is an autogenerated mock type for the TigerbaboonService type
type TigerbaboonService struct {
	mock.Mock
}

type TigerbaboonService_Expecter struct {
	mock *mock.Mock
}

func (_m *TigerbaboonService) EXPECT() *TigerbaboonService_Expecter {
	return &TigerbaboonService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TigerbaboonService
func (_mock *TigerbaboonService) Create(ctx context.Context, username string) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TigerbaboonService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *TigerbaboonService_Expecter) Create(ctx any, username any) *TigerbaboonService_Create_Call {
	return &TigerbaboonService_Create_Call{Call: _e.mock.On("Create", ctx, username)}
}

func (_c *TigerbaboonService_Create_Call) Run(run func(ctx context.Context, username string)) *TigerbaboonService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonService_Create_Call) Return(tigerbaboon *domain.Tigerbaboon, err error) *TigerbaboonService_Create_Call {
	_c.Call.Return(tigerbaboon, err)
	return _c
}

func (_c *TigerbaboonService_Create_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.Tigerbaboon, error)) *TigerbaboonService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TigerbaboonService
func (_mock *TigerbaboonService) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TigerbaboonService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TigerbaboonService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TigerbaboonService_Expecter) Delete(ctx any, id any) *TigerbaboonService_Delete_Call {
	return &TigerbaboonService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TigerbaboonService_Delete_Call) Run(run func(ctx context.Context, id int)) *TigerbaboonService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonService_Delete_Call) Return(err error) *TigerbaboonService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TigerbaboonService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *TigerbaboonService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type TigerbaboonService
func (_mock *TigerbaboonService) GetByID(ctx context.Context, id int) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TigerbaboonService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TigerbaboonService_Expecter) GetByID(ctx any, id any) *TigerbaboonService_GetByID_Call {
	return &TigerbaboonService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TigerbaboonService_GetByID_Call) Run(run func(ctx context.Context, id int)) *TigerbaboonService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonService_GetByID_Call) Return(tigerbaboon *domain.Tigerbaboon, err error) *TigerbaboonService_GetByID_Call {
	_c.Call.Return(tigerbaboon, err)
	return _c
}

func (_c *TigerbaboonService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.Tigerbaboon, error)) *TigerbaboonService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type TigerbaboonService
func (_mock *TigerbaboonService) GetList(ctx context.Context, query domain.ListQuery) (*domain.TigerbaboonList, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *domain.TigerbaboonList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery) (*domain.TigerbaboonList, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery) *domain.TigerbaboonList); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TigerbaboonList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonService_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type TigerbaboonService_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.ListQuery
func (_e *TigerbaboonService_Expecter) GetList(ctx any, query any) *TigerbaboonService_GetList_Call {
	return &TigerbaboonService_GetList_Call{Call: _e.mock.On("GetList", ctx, query)}
}

func (_c *TigerbaboonService_GetList_Call) Run(run func(ctx context.Context, query domain.ListQuery)) *TigerbaboonService_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListQuery
		if args[1] != nil {
			arg1 = args[1].(domain.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonService_GetList_Call) Return(tigerbaboonList *domain.TigerbaboonList, err error) *TigerbaboonService_GetList_Call {
	_c.Call.Return(tigerbaboonList, err)
	return _c
}

func (_c *TigerbaboonService_GetList_Call) RunAndReturn(run func(ctx context.Context, query domain.ListQuery) (*domain.TigerbaboonList, error)) *TigerbaboonService_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TigerbaboonService
func (_mock *TigerbaboonService) Update(ctx context.Context, id int, username string) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, id, username)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, id, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, id, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, id, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TigerbaboonService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - username string
func (_e *TigerbaboonService_Expecter) Update(ctx any, id any, username any) *TigerbaboonService_Update_Call {
	return &TigerbaboonService_Update_Call{Call: _e.mock.On("Update", ctx, id, username)}
}

func (_c *TigerbaboonService_Update_Call) Run(run func(ctx context.Context, id int, username string)) *TigerbaboonService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TigerbaboonService_Update_Call) Return(tigerbaboon *domain.Tigerbaboon, err error) *TigerbaboonService_Update_Call {
	_c.Call.Return(tigerbaboon, err)
	return _c
}

func (_c *TigerbaboonService_Update_Call) RunAndReturn(run func(ctx context.Context, id int, username string) (*domain.Tigerbaboon, error)) *TigerbaboonService_Update_Call {
	_c.Call.Return(run)
	return _c
}
