// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mudflap-autobotz/payment-service-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTigerbaboonRepository creates a new instance of TigerbaboonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTigerbaboonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TigerbaboonRepository {
	mock := &TigerbaboonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TigerbaboonRepository is an autogenerated mock type for the TigerbaboonRepository type
type TigerbaboonRepository struct {
	mock.Mock
}

type TigerbaboonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TigerbaboonRepository) EXPECT() *TigerbaboonRepository_Expecter {
	return &TigerbaboonRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TigerbaboonRepository
func (_mock *TigerbaboonRepository) Create(ctx context.Context, tigerbaboon *domain.Tigerbaboon) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, tigerbaboon)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tigerbaboon) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, tigerbaboon)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tigerbaboon) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, tigerbaboon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Tigerbaboon) error); ok {
		r1 = returnFunc(ctx, tigerbaboon)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TigerbaboonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tigerbaboon *domain.Tigerbaboon
func (_e *TigerbaboonRepository_Expecter) Create(ctx any, tigerbaboon any) *TigerbaboonRepository_Create_Call {
	return &TigerbaboonRepository_Create_Call{Call: _e.mock.On("Create", ctx, tigerbaboon)}
}

func (_c *TigerbaboonRepository_Create_Call) Run(run func(ctx context.Context, tigerbaboon *domain.Tigerbaboon)) *TigerbaboonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Tigerbaboon
		if args[1] != nil {
			arg1 = args[1].(*domain.Tigerbaboon)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonRepository_Create_Call) Return(tigerbaboon1 *domain.Tigerbaboon, err error) *TigerbaboonRepository_Create_Call {
	_c.Call.Return(tigerbaboon1, err)
	return _c
}

func (_c *TigerbaboonRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tigerbaboon *domain.Tigerbaboon) (*domain.Tigerbaboon, error)) *TigerbaboonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TigerbaboonRepository
func (_mock *TigerbaboonRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TigerbaboonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TigerbaboonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TigerbaboonRepository_Expecter) Delete(ctx any, id any) *TigerbaboonRepository_Delete_Call {
	return &TigerbaboonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TigerbaboonRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *TigerbaboonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonRepository_Delete_Call) Return(err error) *TigerbaboonRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TigerbaboonRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *TigerbaboonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type TigerbaboonRepository
func (_mock *TigerbaboonRepository) GetByID(ctx context.Context, id int) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TigerbaboonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TigerbaboonRepository_Expecter) GetByID(ctx any, id any) *TigerbaboonRepository_GetByID_Call {
	return &TigerbaboonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TigerbaboonRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *TigerbaboonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonRepository_GetByID_Call) Return(tigerbaboon *domain.Tigerbaboon, err error) *TigerbaboonRepository_GetByID_Call {
	_c.Call.Return(tigerbaboon, err)
	return _c
}

func (_c *TigerbaboonRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*domain.Tigerbaboon, error)) *TigerbaboonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type TigerbaboonRepository
func (_mock *TigerbaboonRepository) GetList(ctx context.Context, query domain.ListQuery) (*domain.TigerbaboonList, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *domain.TigerbaboonList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery) (*domain.TigerbaboonList, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery) *domain.TigerbaboonList); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TigerbaboonList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type TigerbaboonRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.ListQuery
func (_e *TigerbaboonRepository_Expecter) GetList(ctx any, query any) *TigerbaboonRepository_GetList_Call {
	return &TigerbaboonRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, query)}
}

func (_c *TigerbaboonRepository_GetList_Call) Run(run func(ctx context.Context, query domain.ListQuery)) *TigerbaboonRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListQuery
		if args[1] != nil {
			arg1 = args[1].(domain.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonRepository_GetList_Call) Return(tigerbaboonList *domain.TigerbaboonList, err error) *TigerbaboonRepository_GetList_Call {
	_c.Call.Return(tigerbaboonList, err)
	return _c
}

func (_c *TigerbaboonRepository_GetList_Call) RunAndReturn(run func(ctx context.Context, query domain.ListQuery) (*domain.TigerbaboonList, error)) *TigerbaboonRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TigerbaboonRepository
func (_mock *TigerbaboonRepository) Update(ctx context.Context, tigerbaboon *domain.Tigerbaboon) (*domain.Tigerbaboon, error) {
	ret := _mock.Called(ctx, tigerbaboon)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Tigerbaboon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tigerbaboon) (*domain.Tigerbaboon, error)); ok {
		return returnFunc(ctx, tigerbaboon)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tigerbaboon) *domain.Tigerbaboon); ok {
		r0 = returnFunc(ctx, tigerbaboon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tigerbaboon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Tigerbaboon) error); ok {
		r1 = returnFunc(ctx, tigerbaboon)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TigerbaboonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TigerbaboonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tigerbaboon *domain.Tigerbaboon
func (_e *TigerbaboonRepository_Expecter) Update(ctx any, tigerbaboon any) *TigerbaboonRepository_Update_Call {
	return &TigerbaboonRepository_Update_Call{Call: _e.mock.On("Update", ctx, tigerbaboon)}
}

func (_c *TigerbaboonRepository_Update_Call) Run(run func(ctx context.Context, tigerbaboon *domain.Tigerbaboon)) *TigerbaboonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Tigerbaboon
		if args[1] != nil {
			arg1 = args[1].(*domain.Tigerbaboon)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TigerbaboonRepository_Update_Call) Return(tigerbaboon1 *domain.Tigerbaboon, err error) *TigerbaboonRepository_Update_Call {
	_c.Call.Return(tigerbaboon1, err)
	return _c
}

func (_c *TigerbaboonRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tigerbaboon *domain.Tigerbaboon) (*domain.Tigerbaboon, error)) *TigerbaboonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
