// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWithdrawalService creates a new instance of WithdrawalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalService {
	mock := &WithdrawalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithdrawalService is an autogenerated mock type for the WithdrawalService type
type WithdrawalService struct {
	mock.Mock
}

type WithdrawalService_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalService) EXPECT() *WithdrawalService_Expecter {
	return &WithdrawalService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type WithdrawalService
func (_mock *WithdrawalService) Get(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Withdrawal, error) {
	ret := _mock.Called(ctx, merchantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Withdrawal, error)); ok {
		return returnFunc(ctx, merchantID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Withdrawal); ok {
		r0 = returnFunc(ctx, merchantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, merchantID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WithdrawalService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WithdrawalService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - id uuid.UUID
func (_e *WithdrawalService_Expecter) Get(ctx any, merchantID any, id any) *WithdrawalService_Get_Call {
	return &WithdrawalService_Get_Call{Call: _e.mock.On("Get", ctx, merchantID, id)}
}

func (_c *WithdrawalService_Get_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID)) *WithdrawalService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WithdrawalService_Get_Call) Return(withdrawal *domain.Withdrawal, err error) *WithdrawalService_Get_Call {
	_c.Call.Return(withdrawal, err)
	return _c
}

func (_c *WithdrawalService_Get_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, id uuid.UUID) (*domain.Withdrawal, error)) *WithdrawalService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Initiate provides a mock function for the type WithdrawalService
func (_mock *WithdrawalService) Initiate(ctx context.Context, actor domain.Actor, input domain.InitiateWithdrawal) (*domain.Withdrawal, error) {
	ret := _mock.Called(ctx, actor, input)

	if len(ret) == 0 {
		panic("no return value specified for Initiate")
	}

	var r0 *domain.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Actor, domain.InitiateWithdrawal) (*domain.Withdrawal, error)); ok {
		return returnFunc(ctx, actor, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Actor, domain.InitiateWithdrawal) *domain.Withdrawal); ok {
		r0 = returnFunc(ctx, actor, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Actor, domain.InitiateWithdrawal) error); ok {
		r1 = returnFunc(ctx, actor, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WithdrawalService_Initiate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initiate'
type WithdrawalService_Initiate_Call struct {
	*mock.Call
}

// Initiate is a helper method to define mock.On call
//   - ctx context.Context
//   - actor domain.Actor
//   - input domain.InitiateWithdrawal
func (_e *WithdrawalService_Expecter) Initiate(ctx any, actor any, input any) *WithdrawalService_Initiate_Call {
	return &WithdrawalService_Initiate_Call{Call: _e.mock.On("Initiate", ctx, actor, input)}
}

func (_c *WithdrawalService_Initiate_Call) Run(run func(ctx context.Context, actor domain.Actor, input domain.InitiateWithdrawal)) *WithdrawalService_Initiate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Actor
		if args[1] != nil {
			arg1 = args[1].(domain.Actor)
		}
		var arg2 domain.InitiateWithdrawal
		if args[2] != nil {
			arg2 = args[2].(domain.InitiateWithdrawal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WithdrawalService_Initiate_Call) Return(withdrawal *domain.Withdrawal, err error) *WithdrawalService_Initiate_Call {
	_c.Call.Return(withdrawal, err)
	return _c
}

func (_c *WithdrawalService_Initiate_Call) RunAndReturn(run func(ctx context.Context, actor domain.Actor, input domain.InitiateWithdrawal) (*domain.Withdrawal, error)) *WithdrawalService_Initiate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type WithdrawalService
func (_mock *WithdrawalService) List(ctx context.Context, query domain.WithdrawalQuery) ([]domain.Withdrawal, int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Withdrawal
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WithdrawalQuery) ([]domain.Withdrawal, int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.WithdrawalQuery) []domain.Withdrawal); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.WithdrawalQuery) int64); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.WithdrawalQuery) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// WithdrawalService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WithdrawalService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.WithdrawalQuery
func (_e *WithdrawalService_Expecter) List(ctx any, query any) *WithdrawalService_List_Call {
	return &WithdrawalService_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *WithdrawalService_List_Call) Run(run func(ctx context.Context, query domain.WithdrawalQuery)) *WithdrawalService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.WithdrawalQuery
		if args[1] != nil {
			arg1 = args[1].(domain.WithdrawalQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WithdrawalService_List_Call) Return(withdrawals []domain.Withdrawal, n int64, err error) *WithdrawalService_List_Call {
	_c.Call.Return(withdrawals, n, err)
	return _c
}

func (_c *WithdrawalService_List_Call) RunAndReturn(run func(ctx context.Context, query domain.WithdrawalQuery) ([]domain.Withdrawal, int64, error)) *WithdrawalService_List_Call {
	_c.Call.Return(run)
	return _c
}
