template: testify
dir: internal/domain/mocks
pkgname: mocks
filename: "{{.InterfaceName | snakecase}}.go"
structname: "{{.InterfaceName}}"
packages:
  github.com/mudflap-autobotz/payment-transaction-service/internal/domain:
    interfaces:
      DepositRepository:
      DepositService:
      WithdrawalRepository:
      WithdrawalService:
      EventPublisher:
