// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v3"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/config"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/handler"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/middleware"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/repository"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/repository/tigerbaboon"
	"github.com/mudflap-autobotz/payment-service-go-template/internal/router"
	tigerbaboon2 "github.com/mudflap-autobotz/payment-service-go-template/internal/service/tigerbaboon"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*fiber.App, func(), error) {
	writeDB, cleanup, err := repository.NewWriteDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	readDB, cleanup2, err := repository.NewReadDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tigerbaboonRepository := tigerbaboon.NewTigerbaboonRepository(writeDB, readDB)
	tigerbaboonService := tigerbaboon2.NewTigerbaboonService(tigerbaboonRepository)
	validate := handler.NewValidator()
	tigerbaboonHandler := handler.NewTigerbaboonHandler(tigerbaboonService, validate)
	handlers := &handler.Handlers{
		TigerbaboonHandler: tigerbaboonHandler,
	}
	middlewares := middleware.NewMiddlewares(cfg)
	app := router.NewRouter(cfg, handlers, middlewares)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
