// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v3"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/config"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/handler"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/middleware"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/publisher/kafka"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/repository"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/repository/transaction"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/router"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/service/deposit"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/service/summary"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/service/withdrawal"
	"github.com/mudflap-autobotz/payment-transaction-service/internal/token"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*fiber.App, func(), error) {
	writeDB, cleanup, err := repository.NewWriteDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	readDB, cleanup2, err := repository.NewReadDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	depositRepository := transaction.NewDepositRepository(writeDB, readDB)
	eventPublisher, cleanup3, err := kafka.NewEventPublisher(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	depositService := deposit.NewDepositService(depositRepository, eventPublisher, cfg)
	validate := handler.NewValidator()
	depositHandler := handler.NewDepositHandler(depositService, validate)
	withdrawalRepository := transaction.NewWithdrawalRepository(writeDB, readDB)
	withdrawalService := withdrawal.NewWithdrawalService(withdrawalRepository, eventPublisher, cfg)
	withdrawalHandler := handler.NewWithdrawalHandler(withdrawalService, validate)
	summaryRepository := transaction.NewSummaryRepository(readDB)
	summaryService := summary.NewSummaryService(summaryRepository, cfg)
	summaryHandler := handler.NewSummaryHandler(summaryService)
	handlers := &handler.Handlers{
		DepositHandler:    depositHandler,
		WithdrawalHandler: withdrawalHandler,
		SummaryHandler:    summaryHandler,
	}
	verifier, err := token.NewVerifier(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	middlewares := middleware.NewMiddlewares(cfg, verifier)
	app := router.NewRouter(cfg, handlers, middlewares)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
